POST http://localhost:3333/api/videos
Content-Type: application/json

{
    "title": "Video ",
    "description": "Video 2",
    "duration": "120"
}

###

GET http://localhost:3333/api/videos
Content-Type: application/json
###

GET http://localhost:3333/api/videos/2a98ef92-13b4-42df-bf8c-1ce9fd359fb4
Content-Type: application/json

###

PUT http://localhost:3333/api/videos/2a98ef92-13b4-42df-bf8c-1ce9fd359fb4
Content-Type: application/json

{
    "title": "aaaaa 3",
    "description": "Video 3",
    "duration": "120"
}

###

DELETE http://localhost:3333/api/videos/2a98ef92-13b4-42df-bf8c-1ce9fd359fb4